#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build THE CASTE SYSTEM — वर्ण · जाति (VARNA · JATI · axiom JTI) — the Indian caste system as a
UD0 doctrine-world, built in TWO HONEST LAYERS: LAYER I, वर्ण VARNA — the sacred theory (the four
ritual classes born from the cosmic Purusha, c.1500 BCE, justified by dharma & karma, idealized in
the Manusmriti); and LAYER II, जाति JATI — the lived reality (the thousands of endogamous birth-
groups, hardened over centuries, frozen by the colonial census, abolished in law in 1950 yet kept
alive by endogamy, inherited wealth, and politics). FULLY CITED (24 real sources, superscript-linked
to a Sources apparatus). New SYMMETRIC layout — the Ashoka Chakra header, the vertically-symmetric
PURUSHA cosmic-body diagram, a mirrored two-layer panel, and emergents framed in symmetric JALI
(lattice-screen) windows. Styled to the culture: saffron, India-green, navy chakra, gold, kumkum red,
mandala/rangoli geometry, Devanagari script. Respectful, scholarly cataloguing — caste discrimination
is named plainly and the contested origins kept honest (Steppe migration is genetically real;
'Aryans invented caste' is interpretation)."""
import os, html, base64, io, json, sys, math
sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, r"C:\Davids files\noesis-kernel")
import noesis
from PIL import Image

AX = "JTI"
REC = {
 "name": "THE CASTE SYSTEM", "axiom": AX,
 "position": "वर्ण · जाति — the Indian caste system · c. 1500 BCE – present · catalogued into UD0 in two honest layers",
 "origin": "three thousand years of South Asian society — from the Rigvedic varna ideal to the lived jati order, the colonial census, and the constitutional abolition that the social world has outlived",
 "mechanism": "Built in two layers: the DOCTRINE (varna — four ritual classes born from the cosmic Purusha, sanctified by dharma and karma, idealized in the Dharmashastra) over the REALITY (jati — thousands of endogamous birth-groups, hardened across centuries, enumerated and frozen by British colonial censuses, and sustained today by endogamy, inherited wealth, and electoral politics).",
 "crystallization": "Because caste is the clearest case in the world of a sacred theory and a material reality braided together — and of the honest gap between a thing abolished by law (1950) and a thing regenerated by whom families let their children marry.",
 "nature": "The Indian caste system, in two layers: varna the doctrine and jati the reality — with the origins kept honest, the persistence measured, and the injustice named.",
 "conductor": "ROOT0 (catalogued into UD0 · Universe David 0)",
 "inputs": "the Rigveda (Purusha Sukta 10.90); the Manusmriti; Dumont's Homo Hierarchicus; ancient-DNA genetics (Reich lab, Narasimhan 2019, Moorjani 2013); Dirks' Castes of Mind; the Constitution of India (Art. 17); the Mandal Commission & Indra Sawhney; Pew (2021) & IHDS data; Ambedkar's Annihilation of Caste",
 "witness": "A doctrine ancient enough to be sung to a cosmic body, a reality hard enough to outlive its own legal abolition by seventy-five years — held here in two layers, fully cited, and called by its real names.",
 "role": "a UD0 doctrine-world (two-layer)",
 "seal": "Varna is the hymn; jati is the life. The law abolished it in 1950; marriage, money, and politics renew it every generation. Two layers, honestly told.",
 "source": "The Indian caste system, catalogued by ROOT0",
}

# ───────────────────────── citations (the fully-cited apparatus) ─────────────────────────
# key -> (full reference text, url).  cite() renders a superscript [n]; sources_html() lists them.
CITES = {
 "rv1090":      ("Purusha Sukta — Rigveda Mandala 10, Hymn 90 (RV 10.90.11–12): the cosmic being's mouth/arms/thighs/feet become Brahmin/Rajanya/Vaishya/Shudra — the earliest text placing the four classes together.", "https://en.wikipedia.org/wiki/Varna_(Hinduism)"),
 "rvdate":      ("The Rigveda, the oldest Vedic Sanskrit text, dated by linguistic evidence to c. 1500–1200 BCE (preserved orally for centuries).", "https://en.wikipedia.org/wiki/Rigveda"),
 "embryonic":   ("Jamison & Brereton: 'there is no evidence in the Rigveda for an elaborate… caste system'; the varna scheme is 'embryonic' and Mandala 10 is among the latest books (the verse long held a likely late insertion).", "https://en.wikipedia.org/wiki/Varna_(Hinduism)"),
 "varnajati":   ("Varna (four pan-Indian ritual classes) and jati (the thousands of regional, endogamous birth/occupation groups) are two distinct concepts — commonly estimated at ~3,000 castes and ~25,000 sub-castes.", "https://www.britannica.com/topic/jati-Hindu-caste-system"),
 "avarna":      ("Avarna — those outside the four varnas (Dalits and Adivasis), historically called 'untouchables'/Panchama. Scheduled Castes were ~16.6% of India's population (200M+) in the 2011 Census.", "https://en.wikipedia.org/wiki/Dalit"),
 "karma":       ("Karma & samsara (rebirth): the moral residue of past lives historically framed as justifying one's birth-caste — an interpretive/scholarly characterization, not a uniform doctrine; many Hindu traditions reject equating birth with desert.", "https://en.wikipedia.org/wiki/Karma_in_Hinduism"),
 "manudate":    ("The Manusmriti (Manava Dharmashastra), ~2,000 verses in 12 chapters, composed c. 200 BCE–200 CE (Olivelle: 2nd–3rd c. CE); heavily weighted to the upper varnas (1,034 verses for Brahmins).", "https://en.wikipedia.org/wiki/Manusmriti"),
 "manuideal":   ("Donald Davis: 'no historical evidence for either an active propagation or implementation' of the Manusmriti by any Hindu state; David Buxbaum: 'a Brahmin view of what law ought to be,' not law ever administered.", "https://en.wikipedia.org/wiki/Manusmriti"),
 "dumont":      ("Louis Dumont, Homo Hierarchicus: The Caste System and Its Implications (1966; Univ. of Chicago Press) — the single principle of caste is the opposition of the pure and the impure.", "https://press.uchicago.edu/ucp/books/book/chicago/H/bo25135790.html"),
 "dumontcrit":  ("Berreman, Béteille, Gupta, Mencher: critiques that Dumont's purity/pollution model is a one-sided Brahmanical view that erases power/politics and ignores the auspicious/inauspicious axis.", "https://en.wikipedia.org/wiki/Homo_Hierarchicus"),
 "narasimhan":  ("Narasimhan, Patterson, Moorjani, Reich, et al., 'The formation of human populations in South and Central Asia,' Science 365:6457 (2019), eaat7487 — 523 ancient genomes; Steppe pastoralist ancestry reaches South Asia ~2000–1500 BCE (up to ~30% of modern ancestry).", "https://pmc.ncbi.nlm.nih.gov/articles/PMC6822619/"),
 "reich2009":   ("Reich, Thangaraj, Patterson, Price & Singh, 'Reconstructing Indian population history,' Nature 461 (2009), 489–494 — most Indians descend from two ancestral populations, Ancestral North Indians (ANI) and Ancestral South Indians (ASI).", "https://www.nature.com/articles/nature08365"),
 "moorjani":    ("Moorjani, Thangaraj, Patterson, Reich, et al., 'Genetic Evidence for Recent Population Mixture in India,' Am. J. Hum. Genet. 93 (2013), 422–438 — ANI–ASI admixture dates ~1,900–4,200 years ago, after which India shifted to widespread endogamy.", "https://www.cell.com/AJHG/fulltext/S0002-9297(13)00324-8"),
 "reichbook":   ("David Reich, Who We Are and How We Got Here (2018): caste has 'been around for a long time, but not forever'; genetics dates the hardening of endogamy/jati boundaries, NOT the invention of the varna ideology.", "https://en.wikipedia.org/wiki/Who_We_Are_and_How_We_Got_Here"),
 "metcalf":     ("Barbara & Thomas Metcalf: until relatively recent centuries much of the subcontinent was 'little touched by the four varnas'; a recognizably rigid caste system emerges around the early-modern era; jati crystallized post-Mauryan to medieval.", "https://en.wikipedia.org/wiki/Castes_of_Mind"),
 "dirks":       ("Nicholas Dirks, Castes of Mind: Colonialism and the Making of Modern India (Princeton, 2001) — the decennial colonial census (from 1871–72) showed an 'intolerance for multiple, blurred, changing identities,' rigidifying caste into fixed all-India categories.", "https://press.princeton.edu/books/paperback/9780691088952/castes-of-mind"),
 "art17":       ("Constitution of India (adopted 1949, in force 26 Jan 1950), Article 17: \"'Untouchability' is abolished and its practice in any form is forbidden… an offence punishable in accordance with law.\"", "https://www.constitutionofindia.net/articles/article-17-abolition-of-untouchability/"),
 "ambedkar":    ("B.R. Ambedkar (1891–1956), Dalit-born jurist, chair of the Constitution's Drafting Committee and first Law Minister; wrote Annihilation of Caste (1936, self-published after a reform group found it too radical); converted to Buddhism with ~500,000 followers in 1956.", "https://www.barbri.com/resources/br-ambedkar-from-untouchable-to-indias-first-minister-of-law-justice"),
 "mandal":      ("The Mandal Commission (report 1980, implemented Aug 1990) recommended 27% reservation for Other Backward Classes; Indra Sawhney v. Union of India (1992) upheld it, capped total reservation at 50%, and added the 'creamy layer' exclusion.", "https://www.drishtiias.com/daily-updates/daily-news-analysis/mandal-commission-1"),
 "ihds":        ("India Human Development Survey (IHDS-II): only ~5.8% of marriages were inter-caste as of 2011, roughly flat from 1970–2012; ~73% of marriages were parent-arranged — endogamy is among the most resilient caste practices.", "https://www.isid.ac.in/~tridip/Research/IntercasteMarriage_18February2020.pdf"),
 "pew":         ("Pew Research Center, 'Religion in India: Tolerance and Segregation' (2021; 29,999 adults): 98% of Indians identify with a caste; 64% say it is very important to stop women (62% men) from marrying into another caste — even ~half of college-educated Indians agree.", "https://www.pewresearch.org/religion/2021/06/29/attitudes-about-caste/"),
 "scavenging":  ("~77% of India's manual scavengers are Dalit; the practice is banned (Prohibition of Employment as Manual Scavengers Act, 2013) yet persists, with recorded sewer/septic-tank deaths each year.", "https://www.thenewsminute.com/news/77-of-manual-scavengers-are-dalit-says-report-despite-union-govts-denial"),
 "bhakti":      ("An anti-caste lineage predates colonialism: the Buddha and the Shramana traditions, and Bhakti saints — Ravidas (the casteless 'Begumpura'), Kabir, and Basava (who promoted inter-caste marriage and dining).", "https://countercurrents.org/2024/10/bhakti-kal-and-caste-question/"),
 "hrw":         ("Human Rights Watch, Hidden Apartheid: Caste Discrimination against India's 'Untouchables' (2007) — documents systemic, ongoing discrimination and violence.", "https://www.hrw.org/report/2007/02/12/hidden-apartheid/caste-discrimination-against-indias-untouchables"),
}
CKEYS = list(CITES.keys())
def cnum(key): return CKEYS.index(key) + 1
def cite(*keys):
    return "".join(f'<sup class="c"><a href="#s-{k}" title="{html.escape(CITES[k][0][:120])}">[{cnum(k)}]</a></sup>' for k in keys)
def sources_html():
    out=['<ol class="srcs">']
    for k in CKEYS:
        txt,url=CITES[k]
        out.append(f'<li id="s-{k}"><span class="snum">[{cnum(k)}]</span> {html.escape(txt)} <a class="surl" href="{url}" target="_blank" rel="noopener">↗ source</a></li>')
    out.append('</ol>'); return "".join(out)

# nature → (colour, gloss) — tuned to the Indian palette & to caste
NATURES = {
 "spiritual": ("#ff9933", "the sacred — the cosmic order, dharma & karma, the scriptural ideal and the saints who refused it"),
 "ethereal":  ("#d4af37", "the doctrine — varna theory, the law-books, purity & pollution; the structure as written"),
 "electrical":("#c0392b", "the machinery — enforcement and power: the census, endogamy as engine, reservations, the politics of caste"),
 "natural":   ("#2e8b3d", "the lived — jati and the body: occupation, the village, the people, and what the genetics records"),
}
LAYERS = {
 "doctrine": ("#d4af37", "वर्ण VARNA — the sacred theory", "what caste claims to be: four ritual classes born from a cosmic body, sanctified by dharma and karma"),
 "reality":  ("#2e8b3d", "जाति JATI — the lived reality", "what caste actually is: thousands of endogamous birth-groups, hardened by history, frozen by colonial counting, renewed by marriage and politics"),
}

# ───────────────────────── the SVG showpieces (symmetric, cultural) ─────────────────────────
def chakra_svg(size=120, stroke="#1a2a6c", spokes=24):
    c=size/2; r=size*0.42; hub=size*0.07
    parts=[f'<svg viewBox="0 0 {size} {size}" width="{size}" height="{size}" xmlns="http://www.w3.org/2000/svg" aria-label="Ashoka Chakra">',
           f'<circle cx="{c}" cy="{c}" r="{r}" fill="none" stroke="{stroke}" stroke-width="{size*0.035:.1f}"/>']
    for i in range(spokes):
        a=2*math.pi*i/spokes
        x2=c+r*math.cos(a); y2=c+r*math.sin(a)
        parts.append(f'<line x1="{c:.1f}" y1="{c:.1f}" x2="{x2:.2f}" y2="{y2:.2f}" stroke="{stroke}" stroke-width="{size*0.014:.2f}"/>')
        # little spoke-pin at the rim (the Ashoka chakra's 24 spokes have rounded ends)
        parts.append(f'<circle cx="{x2:.2f}" cy="{y2:.2f}" r="{size*0.012:.2f}" fill="{stroke}"/>')
    parts.append(f'<circle cx="{c}" cy="{c}" r="{hub}" fill="{stroke}"/>')
    parts.append('</svg>')
    return "".join(parts)

def purusha_svg():
    """The Purusha — the cosmic body whose parts become the four varnas; the Dalits below, outside.
    Vertically symmetric about x=210. viewBox 0 0 420 600."""
    cx=210
    saff="#ff9933"; gold="#d4af37"; green="#2e8b3d"; red="#c0392b"; navy="#1a2a6c"; ivory="#f4e9d8"; grey="#6b6360"
    p=[f'<svg viewBox="0 0 420 600" xmlns="http://www.w3.org/2000/svg" class="purusha" role="img" aria-label="The Purusha: the four varnas born from the cosmic body, with the Dalits placed outside it">']
    # concentric mandala rings behind
    for i,rr in enumerate([250,205,160]):
        p.append(f'<circle cx="{cx}" cy="270" r="{rr}" fill="none" stroke="{gold}" stroke-opacity="{0.10+0.04*i:.2f}" stroke-width="1"/>')
    # 16 faint mandala spokes
    for i in range(16):
        a=2*math.pi*i/16; x2=cx+250*math.cos(a); y2=270+250*math.sin(a)
        p.append(f'<line x1="{cx}" y1="270" x2="{x2:.1f}" y2="{y2:.1f}" stroke="{gold}" stroke-opacity="0.05" stroke-width="1"/>')
    # ---- the body, top to bottom, each zone a varna ----
    # HEAD / MOUTH = Brahmin
    p.append(f'<circle cx="{cx}" cy="90" r="46" fill="{saff}" fill-opacity="0.22" stroke="{saff}" stroke-width="2"/>')
    p.append(f'<path d="M180 100 Q210 122 240 100" fill="none" stroke="{saff}" stroke-width="3"/>')  # the mouth
    # ARMS = Kshatriya  (symmetric)
    p.append(f'<path d="M150 175 Q90 200 78 270" fill="none" stroke="{red}" stroke-width="14" stroke-linecap="round" stroke-opacity="0.85"/>')
    p.append(f'<path d="M270 175 Q330 200 342 270" fill="none" stroke="{red}" stroke-width="14" stroke-linecap="round" stroke-opacity="0.85"/>')
    # TORSO / THIGHS = Vaishya
    p.append(f'<path d="M160 165 L260 165 L246 360 L174 360 Z" fill="{gold}" fill-opacity="0.20" stroke="{gold}" stroke-width="2"/>')
    # LEGS / FEET = Shudra (symmetric)
    p.append(f'<path d="M178 360 L204 360 L200 470 L176 470 Z" fill="{green}" fill-opacity="0.22" stroke="{green}" stroke-width="2"/>')
    p.append(f'<path d="M216 360 L242 360 L244 470 L220 470 Z" fill="{green}" fill-opacity="0.22" stroke="{green}" stroke-width="2"/>')
    p.append(f'<ellipse cx="188" cy="482" rx="22" ry="9" fill="{green}" fill-opacity="0.3" stroke="{green}" stroke-width="1.5"/>')
    p.append(f'<ellipse cx="232" cy="482" rx="22" ry="9" fill="{green}" fill-opacity="0.3" stroke="{green}" stroke-width="1.5"/>')
    # the ground line, and OUTSIDE/BELOW it = the Dalits (avarna)
    p.append(f'<line x1="40" y1="508" x2="380" y2="508" stroke="{ivory}" stroke-opacity="0.35" stroke-dasharray="5 5" stroke-width="1.5"/>')
    p.append(f'<circle cx="{cx}" cy="548" r="26" fill="none" stroke="{grey}" stroke-width="2" stroke-dasharray="4 4"/>')
    # ---- labels (symmetric, with body-part + Devanagari) ----
    def lab(x,y,anchor,dev,name,part,col):
        ax={"start":"start","middle":"middle","end":"end"}[anchor]
        return (f'<text x="{x}" y="{y}" text-anchor="{ax}" font-family="Tiro Devanagari Sanskrit,serif" font-size="17" fill="{col}">{dev}</text>'
                f'<text x="{x}" y="{y+18}" text-anchor="{ax}" font-family="Rozha One,serif" font-size="15" fill="{ivory}">{name}</text>'
                f'<text x="{x}" y="{y+34}" text-anchor="{ax}" font-family="Space Mono,monospace" font-size="9.5" fill="{col}" letter-spacing="1">{part}</text>')
    p.append(lab(cx,40,"middle","ब्राह्मण","Brahmin","THE MOUTH",saff))
    p.append(lab(372,250,"end","क्षत्रिय","Kshatriya","THE ARMS",red))
    p.append(lab(372,330,"end","वैश्य","Vaishya","THE THIGHS",gold))
    p.append(lab(372,455,"end","शूद्र","Shudra","THE FEET",green))
    p.append(lab(cx,598,"middle","दलित","Dalit · avarna","OUTSIDE THE BODY",grey))
    # left-side note
    p.append(f'<text x="48" y="250" text-anchor="start" font-family="Space Mono,monospace" font-size="9" fill="{ivory}" fill-opacity="0.55">RV 10.90</text>')
    p.append(f'<text x="48" y="264" text-anchor="start" font-family="Space Mono,monospace" font-size="9" fill="{ivory}" fill-opacity="0.55">the Purusha</text>')
    p.append('</svg>')
    return "".join(p)

# ───────────────────────── the historical arc ─────────────────────────
ARC_OVERALL = ("Caste is not one thing with one origin. An ancient ritual theory (varna) and a sprawling lived reality (jati) "
  "braided together over three thousand years, were sanctified by scripture, idealized in the law-books, hardened across the "
  "medieval and early-modern centuries, frozen into fixed all-India categories by British colonial censuses, abolished in law "
  "by the 1950 Constitution — and then outlived that abolition, because law can forbid a practice overnight but cannot forbid "
  "whom a family lets its children marry.")
ARC = [
 ("I · the hymn", "c. 1500–1200 BCE", "spiritual",
  "The Rigveda's Purusha Sukta (10.90) sings society out of a cosmic body — Brahmin from the mouth, Kshatriya from the arms, Vaishya from the thighs, Shudra from the feet. But the varna scheme is only 'embryonic' here; this verse is in one of the latest books and was long suspected a late insertion.", ["rv1090","rvdate","embryonic"]),
 ("II · the law-books", "c. 200 BCE – 200 CE", "ethereal",
  "The Manusmriti and the Dharmashastra literature codify duties, purity, occupation, and intermarriage by varna — overwhelmingly from a Brahmin point of view. Scholars stress these were idealized prescriptions: there is no evidence any Hindu state actually administered the Manusmriti as law.", ["manudate","manuideal"]),
 ("III · the crystallizing", "post-Mauryan → medieval", "natural",
  "The lived order — jati — slowly hardens: occupational guilds close into endogamous birth-groups, and genetics records the shift to strict endogamy taking hold roughly 2,000 years ago. Historians read a long, gradual closure, not a single decree.", ["moorjani","metcalf"]),
 ("IV · the counting", "1871–1931", "electrical",
  "The British decennial census enumerates and ranks every caste into fixed, all-India categories. Nicholas Dirks argues this colonial 'intolerance for blurred identities' rigidified what had been more fluid and regional — modern, nation-wide caste owes a great deal to being counted.", ["dirks"]),
 ("V · the abolition", "1936 → 1950", "electrical",
  "Ambedkar — Dalit-born, the Constitution's chief draftsman — writes Annihilation of Caste (1936), and the 1950 Constitution's Article 17 abolishes untouchability outright. The doctrine is broken in law.", ["ambedkar","art17"]),
 ("VI · the afterlife", "1950 → now", "natural",
  "Yet 98% of Indians still identify with a caste, only ~5.8% of marriages cross caste lines, and 64% say it is very important to stop women marrying out. Reservations make caste a permanent administrative category; endogamy, inherited wealth, and vote-banks renew it. The law won; the social world has not yet followed.", ["pew","ihds","mandal"]),
]

# ───────────────────────── Real or Fluff (honest, cited) ─────────────────────────
REALFLUFF = [
 ("‘Caste is purely ancient and scriptural’", "PARTLY", "the doctrine IS ancient (the varna hymn is c.1500 BCE), but the rigid, nation-wide caste SYSTEM is substantially early-modern, and was sharpened by colonial census categorization — old roots, but a much newer trunk", ["rvdate","metcalf","dirks"]),
 ("‘The Aryans invented and imposed caste’", "INTERPRETATION, NOT PROOF", "a real influx of Steppe ancestry reached South Asia ~2000–1500 BCE (genetically demonstrated), and endogamy set in ~2,000 yrs ago — but that incoming groups INVENTED caste is an inference, not a genetic result; historians lean toward gradual internal development", ["narasimhan","moorjani","reichbook"]),
 ("‘Varna and jati are the same thing’", "FALSE — A CONFLATION", "varna is the four-fold ritual THEORY; jati is the lived reality of ~3,000 endogamous birth-groups (and ~25,000 sub-groups). They never mapped cleanly onto each other — that gap is the whole story", ["varnajati"]),
 ("‘The Manusmriti was India's enforced law code’", "FLUFF", "it was a Brahmin ideal of what law ought to be; there is 'no historical evidence' that any Hindu state propagated or implemented it as administered law (Davis, Buxbaum)", ["manuideal"]),
 ("‘Caste is gone in modern India — it's just rural’", "FALSE", "it is illegal, not gone: 98% identify with a caste, only ~5.8% of marriages are inter-caste, and 64% want to stop women marrying across caste — discrimination is starker in villages but follows surnames and networks into the cities", ["pew","ihds"]),
 ("‘Reservations are just reverse discrimination’", "CONTESTED — A VALUES CALL", "a genuine justice instrument (SC/ST/OBC quotas, capped at 50%, with a 'creamy layer' exclusion) that lifts the historically excluded — and which also, by design, makes caste a permanent electoral and administrative category; not a fact, a tradeoff", ["mandal"]),
 ("‘Caste is only a Hindu phenomenon’", "NUANCED", "it originates in the Hindu varna order, but Pew finds Indians of every religion identify with caste, and Dalit Muslims, Christians, and Sikhs exist — the social structure outran the theology that bore it", ["pew","bhakti"]),
]
REALFLUFF_VERDICT = ("Bottom line, kept honest: the doctrine is genuinely ancient but the rigid all-India SYSTEM is far newer and was hardened "
  "by colonial counting; the Steppe migration is real genetics while 'the Aryans invented caste' is interpretation; the Manusmriti "
  "was an ideal, not an enforced code; and caste is abolished in law yet vividly alive in marriage, wealth, and politics. The origins "
  "are a live academic AND nationalist battleground — anyone who tells you they're settled is selling something. What is NOT in "
  "doubt is the injustice: untouchability, manual scavenging that is ~77% Dalit, and honor violence over inter-caste marriage are "
  "documented and ongoing.")

MESSAGE = ("Two layers, and the gap between them is the truth of the thing. The top layer — varna — is a hymn: a cosmos sung into a "
  "body, four classes from a mouth and arms and thighs and feet, sanctified by karma so that your birth feels like justice. The "
  "bottom layer — jati — is a life: three thousand endogamous groups, a surname that gives you away, a marriage your family arranges "
  "inside the line. The doctrine was never really the engine; you can stop believing the cosmic hymn and the system still runs, "
  "because what regenerates caste is not faith but practice — whom you may marry, what your parents owned, which box the State and the "
  "ballot put you in. That is why Ambedkar aimed not at the gods but at the marriage and the law, and why he could win the Constitution "
  "and still lose the village. Law can abolish a doctrine in a day. It cannot, by itself, abolish a reality that renews itself every "
  "wedding season. The honest reading is neither 'it's ancient and sacred' nor 'it's gone' — it is that a sacred theory and a material "
  "reality were braided so tightly that cutting one strand left the other intact, and the work of untying the second has barely begun.")
MESSAGE_SEAL = "Varna is the hymn; jati is the life. The law abolished it in 1950; marriage, money, and the ballot renew it every generation. Honesty is the only solvent left."

# ───────────────────────── ACI complement ─────────────────────────
def carbon_tiff_bytes(rec):
    png = noesis.sigil_png(rec, "carbon", size=512)
    buf = io.BytesIO(); Image.open(io.BytesIO(png)).save(buf, "TIFF", compression="tiff_lzw")
    return buf.getvalue()
def write_aci(rec, out_dir, slug, agent_md=None):
    os.makedirs(out_dir, exist_ok=True)
    f = {"attribute":f"{slug}.attribute","agent":f"{slug}.agent","spun":f"{slug}.spun","moniker":f"{slug}.moniker",
         "carbon":f"{slug}.carbon.tiff","silicon":f"{slug}.silicon.png","1099":f"{slug}.1099"}
    tok = noesis.mythos_token(rec); w = noesis.five_w(rec)
    open(os.path.join(out_dir,f["attribute"]),"w",encoding="utf-8").write(noesis.attribute_text(rec,tok,w))
    open(os.path.join(out_dir,f["agent"]),"w",encoding="utf-8").write(agent_md or noesis.agent_text(rec,tok,w,f))
    open(os.path.join(out_dir,f["spun"]),"w",encoding="utf-8").write(noesis.spun_text(rec,tok,w,rec.get("axiom",AX)))
    open(os.path.join(out_dir,f["moniker"]),"w",encoding="utf-8").write(noesis.moniker_text(rec,tok,w,rec.get("axiom",AX)))
    open(os.path.join(out_dir,f["1099"]),"w",encoding="utf-8").write(noesis.credit_1099_text(rec,tok,w,rec.get("axiom",AX)))
    open(os.path.join(out_dir,f["carbon"]),"wb").write(carbon_tiff_bytes(rec))
    open(os.path.join(out_dir,f["silicon"]),"wb").write(noesis.sigil_png(rec,"silicon",512))
    return {"slug":slug,"name":rec["name"],"moniker":tok["moniker"],"seal_sha256":noesis.seal_sha256(rec,tok),
            "architect":noesis.ARCHITECT,"instance":noesis.INSTANCE,"license":noesis.LICENSE,"attribution":noesis.ATTRIBUTION}
def png_uri(rec, variant, size=300):
    return "data:image/png;base64," + base64.b64encode(noesis.sigil_png(rec, variant, size=size)).decode("ascii")

def E(slug,name,dev,cls,layer,em,who,what,why,how,where,seal,cites=None,figure=""):
    return dict(slug=slug,name=name,dev=dev,cls=cls,layer=layer,emergence=em,who=who,what=what,why=why,how=how,
                where=where,seal=seal,cites=cites or [],figure=figure)

ROSTER = [
 # ═══════════════ LAYER I — वर्ण THE DOCTRINE (the sacred theory) ═══════════════
 E("purusha","Purusha","पुरुष","the cosmic body · RV 10.90","doctrine","spiritual",
   "Purusha — the primeval cosmic being of the Rigveda's Purusha Sukta, sacrificed by the gods so that the world (and society) is made from the parts of its body.",
   "The origin-image of varna: from the being's mouth came the Brahmin, its arms the Kshatriya, its thighs the Vaishya, its feet the Shudra — society as a single sacrificed body. Yet the verse is in one of the latest Rigvedic books and the varna scheme is only 'embryonic' there.",
   "Because this single hymn is the scriptural seed of the entire doctrine — the moment hierarchy is given a cosmic body.",
   "By the myth of a primal sacrifice (the purushamedha) from which the four classes, and the cosmos, emerge.",
   "Rigveda Mandala 10, Hymn 90 — the oldest text placing the four classes together.",
   "From my mouth, arms, thighs, and feet they made the four — and called a hierarchy the shape of a body. But I am a late hymn, not the first word.",
   cites=["rv1090","rvdate","embryonic"]),
 E("varna","Varna","वर्ण","the four-fold ritual order","doctrine","ethereal",
   "Varna — the theory: a pan-Indian classification of society into four ranked ritual classes (plus those left outside).",
   "The doctrine layer itself — abstract, scriptural, and nation-wide in principle; four classes ranked by ritual purity. Distinct from jati, the thousands of birth-groups actually lived.",
   "Because varna is the IDEA of caste — the clean four-fold map that never matched the messy ground.",
   "By scriptural sanction and the logic of ritual purity, ranking the classes mouth-to-feet.",
   "The texts and the theology; the top layer of the two.",
   "I am the map, not the territory — four tidy classes over a land of three thousand birth-groups that never fit me.",
   cites=["varnajati","rv1090"]),
 E("brahmin","Brahmin","ब्राह्मण","the mouth · priests & scholars","doctrine","spiritual",
   "Brahmin — born of the Purusha's mouth; the priestly and scholarly varna, custodians of the Vedas and ritual.",
   "The highest ritual class: priests, teachers, keepers of liturgy and purity. The Manusmriti's verses overwhelmingly concern them — and ancient-DNA shows traditionally priestly groups carry somewhat more Steppe ancestry (a correlation, not a cause).",
   "Because the mouth that speaks the sacred word sits at the top of the purity order — the class the whole doctrine is written from.",
   "By Vedic learning, ritual authority, and the guardianship of purity.",
   "The mouth of the cosmic body; the top of the varna order.",
   "I am the mouth that speaks the Veda — the doctrine was written in my voice, which is exactly why it ranks me first.",
   cites=["rv1090","manudate","narasimhan"]),
 E("kshatriya","Kshatriya","क्षत्रिय","the arms · warriors & rulers","doctrine","electrical",
   "Kshatriya (Rigvedic 'Rajanya') — born of the Purusha's arms; the warrior and ruling varna.",
   "The class of kings, warriors, and administrators — prowess, protection, governance. The arms that hold the weapon and the throne, ranked second below the priestly mouth.",
   "Because power needed a sacred place in the order too — the sword and the crown, blessed but below the priest.",
   "By martial prowess, rule, and the protection of the realm and its dharma.",
   "The arms of the cosmic body; the second varna.",
   "I hold the sword and the throne — and still the hymn puts the mouth above the arm, the blessing above the blade.",
   cites=["rv1090"]),
 E("vaishya","Vaishya","वैश्य","the thighs · merchants & farmers","doctrine","natural",
   "Vaishya — born of the Purusha's thighs; the varna of merchants, farmers, herders, and traders.",
   "The productive class: agriculture, cattle, commerce — the body's thighs that bear its weight. Twice-born (entitled to Vedic study) yet ranked below the warrior.",
   "Because the doctrine needed the producers placed and ranked — wealth and harvest given their tier.",
   "By trade, farming, and herding — the economic engine of the classical order.",
   "The thighs of the cosmic body; the third varna.",
   "I grow the grain and move the goods that feed the order — counted among the twice-born, and still set beneath the sword.",
   cites=["rv1090","varnajati"]),
 E("shudra","Shudra","शूद्र","the feet · laborers & servants","doctrine","natural",
   "Shudra — born of the Purusha's feet; the varna of laborers, artisans, and servants of the three above.",
   "The fourth class, tasked with serving the higher three and barred from much religious participation — the feet on which the body stands, ranked lowest within the four (but still inside them).",
   "Because the doctrine needed hands to do the work, placed at the bottom of the ranked body — yet, crucially, still within varna, unlike the Dalits.",
   "By labor and service, and by exclusion from the rites reserved to the twice-born.",
   "The feet of the cosmic body; the fourth and lowest varna.",
   "I am the feet the body stands on — lowest of the four, but inside the body; below me the doctrine put those it would not count at all.",
   cites=["rv1090","manudate"]),
 E("dharma","Dharma","धर्म","righteous duty · one's proper role","doctrine","spiritual",
   "Dharma — righteous duty; in the caste doctrine, the duty proper to one's varna (svadharma).",
   "The ethical glue of the order: each class has its own dharma, and to fulfill the duty of your station — even a lowly one — is framed as the righteous path (the Gita's counsel to Arjuna).",
   "Because dharma turns a social position into a moral vocation — it makes staying in your place a virtue.",
   "By assigning each varna its proper conduct, and teaching that one's own duty done imperfectly beats another's done well.",
   "The moral law woven through the whole doctrine.",
   "I make your station feel like your sacred task — which is how a hierarchy gets a soul, and a cage gets called a calling.",
   cites=["karma"]),
 E("karma","Karma & Samsara","कर्म · संसार","rebirth · the moral ledger","doctrine","spiritual",
   "Karma and samsara — the moral residue of past actions and the cycle of rebirth; the engine that, in this framing, explains one's birth-caste.",
   "The deep rationale: if the soul is reborn by its karma, then birth into a given caste can be read as the just wage of past lives — a spiritual justification for the social order. (This 'karma justifies caste' reading is an interpretive thesis, not uniform doctrine; many traditions reject it.)",
   "Because nothing entrenches a hierarchy like making it feel cosmically deserved — karma turns accident of birth into moral arithmetic.",
   "By the doctrine of rebirth, in which present station is the ledger of past conduct.",
   "The metaphysics beneath the order.",
   "I tell you your birth was earned — the most powerful sentence a hierarchy ever spoke, and the one Ambedkar refused.",
   cites=["karma"]),
 E("manusmriti","The Manusmriti","मनुस्मृति","the law-book · the ideal","doctrine","ethereal",
   "The Manusmriti (Manava Dharmashastra) — the most cited of the Hindu law-books, ~2,000 verses codifying duty, purity, and caste.",
   "The doctrine written down: duties by varna, rules of purity and intermarriage, the subordination of the Shudra — overwhelmingly from a Brahmin viewpoint. But scholars are clear it was an IDEAL: 'no historical evidence' that any state administered it as law.",
   "Because this is where the theory hardened into text — and where the honest gap between 'what was written' and 'what was enforced' is starkest.",
   "By prescription, not administration — a vision of what law ought to be, later treated as if it had been law.",
   "Composed c. 200 BCE – 200 CE; burned in protest by Ambedkar in 1927.",
   "I am what the order WROTE about itself — a Brahmin's ideal, mistaken for a kingdom's code; Ambedkar burned me to say so.",
   cites=["manudate","manuideal","ambedkar"]),
 E("purity","Purity & Pollution","शुद्धि","the ritual logic · Dumont","doctrine","ethereal",
   "Purity and pollution — the ritual logic that, in Louis Dumont's classic thesis, organizes the whole caste hierarchy.",
   "The structuralist account (Homo Hierarchicus, 1966): caste rank tracks ritual purity, and separation (who may touch, dine, marry whom) enforces it. Powerfully influential — and heavily criticized for being a one-sided Brahmanical view that erases power and politics.",
   "Because purity/pollution is the most elegant single explanation of caste behaviour — and its critique is a lesson in not mistaking the priest's view for the whole.",
   "By rules of contact, commensality, and endogamy that keep the 'pure' apart from the 'polluting.'",
   "The contested heart of caste theory.",
   "I rank the world by clean and unclean — an elegant key, and a Brahmin's one; the critics say I hid the power behind the purity.",
   cites=["dumont","dumontcrit"]),

 # ═══════════════ LAYER II — जाति THE REALITY (the lived order) ═══════════════
 E("jati","Jati","जाति","the thousands of birth-groups","reality","natural",
   "Jati — 'birth'; the thousands of local, endogamous, hereditary, occupation-linked communities that people actually belong to and marry within.",
   "The reality layer: ~3,000 castes and ~25,000 sub-castes, regional and specific — the lived unit of caste, which the four tidy varnas never mapped onto. This is what 'caste' means on the ground.",
   "Because jati, not varna, is where caste is lived, married, and inherited — the territory under the doctrine's map.",
   "By birth, endogamy, hereditary occupation, and local hierarchy — negotiated and regional, not nation-wide.",
   "Everywhere caste is actually practiced; the bottom layer of the two.",
   "I am the life the doctrine only mapped — three thousand of me, each a wall around a marriage, and not one of us fits the hymn's neat four.",
   cites=["varnajati"]),
 E("dalit","The Dalits","दलित","outside the body · 'untouchables'","reality","natural",
   "The Dalits ('broken/scattered'; formerly 'untouchables,' avarna) — those placed OUTSIDE the four varnas entirely, and the people the doctrine harmed most.",
   "Roughly 16.6% of India (200M+ as Scheduled Castes): historically barred from temples, wells, and touch; assigned the work deemed 'polluting.' Named here with dignity — not a metaphor, but living people the order excluded.",
   "Because the cruelest fact of the system is the line BELOW the four — the human beings ranked outside the cosmic body altogether.",
   "By exclusion from varna, segregation, and the assignment of 'impure' labor — and, against it, by Ambedkar, the Constitution, and their own movements.",
   "Outside and below the Purusha's body; at the center of the fight to end caste.",
   "They put us outside the body of the world — and we wrote the Constitution that abolished the line. Dalit means broken; it also means unbroken.",
   cites=["avarna","art17","ambedkar"]),
 E("ambedkar","B.R. Ambedkar","आम्बेडकर","the architect & the breaker","reality","spiritual",
   "Bhimrao Ramji Ambedkar (1891–1956) — Dalit-born jurist and economist, chief architect of the Indian Constitution, and the towering opponent of caste.",
   "A real historical person, catalogued with full respect: he wrote Annihilation of Caste (1936), drafted Article 17 abolishing untouchability, and in 1956 led ~500,000 Dalits in converting to Buddhism — rejecting the doctrine at its metaphysical root.",
   "Because the system's deepest critic also became the author of the law that abolished it — and aimed not at the gods but at the marriage and the statute.",
   "By scholarship, constitutional law, mass conversion, and the burning of the Manusmriti (1927); by refusing the karma that called his birth deserved.",
   "From an 'untouchable' birth to the drafting table of the Republic.",
   "They ranked me outside the body of the world; I wrote the body of its law. Annihilate caste — not the casteless, the caste itself.",
   cites=["ambedkar","art17"], figure="B.R. Ambedkar · 1891–1956 · real historical person"),
 E("endogamy","Endogamy","अंतर्विवाह","the engine · marriage within","reality","electrical",
   "Endogamy — marriage strictly within one's caste; the single most durable mechanism that regenerates caste every generation.",
   "The real engine: genetics shows strict endogamy set in ~2,000 years ago (founder effects rivaling Ashkenazi Jews or Finns), and today only ~5.8% of Indian marriages cross caste — flat for four decades. As long as marriage is endogamous, the boundaries self-replicate.",
   "Because this, not belief, is what keeps caste alive — the doctrine can fade, but a wall around the wedding renews the group forever.",
   "By arranged marriage within jati, social pressure, and (historically) violence against those who marry out.",
   "The bedrock mechanism, ancient and ongoing.",
   "Stop believing the hymn and I still run — because caste is not in the prayer, it is in the marriage, and that you still arrange inside the line.",
   cites=["moorjani","ihds"]),
 E("steppe","The Steppe Migration","—","the contested origin · the DNA","reality","natural",
   "The ancient-DNA evidence: a real influx of Steppe pastoralist ancestry into South Asia ~2000–1500 BCE — and the honest limit of what it proves.",
   "Genetically demonstrated (Reich lab; Narasimhan 2019, 523 ancient genomes): Steppe ancestry arrived after the Indus decline and is up to ~30% of modern South Asian ancestry, somewhat enriched in priestly groups. NOT demonstrated: that these migrants 'invented' caste — that is interpretation; endogamy dates later.",
   "Because the origins are a live academic AND nationalist battleground — and the only honest line is between the demonstrated migration and the inferred causation.",
   "By whole-genome sequencing of ancient and modern populations, and the ANI/ASI ancestral model.",
   "The deep past, read from DNA and argued over in the present.",
   "Yes, people came from the Steppe ~2000–1500 BCE — that is real. That they 'invented' caste is a story laid over a fact; I record the fact, not the story.",
   cites=["narasimhan","reich2009","moorjani","reichbook"]),
 E("census","The Colonial Census","—","the hardening · counted & frozen","reality","electrical",
   "The British colonial census — which, from 1871, enumerated and ranked every caste into fixed, all-India categories.",
   "Nicholas Dirks' thesis (Castes of Mind, 2001): the census's 'intolerance for multiple, blurred, changing identities' turned fluid, regional, negotiable caste into rigid, bureaucratic, nation-wide categories. Modern caste-as-a-single-system owes much to colonial counting.",
   "Because this is the hinge between the old fluidity and the modern rigidity — the moment caste was frozen by being measured.",
   "By decennial enumeration, ranking, and the administrative demand that every person fit one fixed caste box.",
   "British India, 1871–1931; the making of 'modern' caste.",
   "I counted you, and in counting froze you — what had been blurred and regional I made fixed and national; you inherited my categories.",
   cites=["dirks","metcalf"]),
 E("article17","Article 17 · the Constitution","अनुच्छेद १७","the abolition in law","reality","electrical",
   "Article 17 of the Constitution of India (1950) — 'Untouchability is abolished and its practice in any form is forbidden.'",
   "The legal break: drafted under Ambedkar, the Constitution outlawed untouchability and caste discrimination outright (Arts. 15, 17), backed by criminal statute. Caste discrimination became, overnight, illegal.",
   "Because this is the cleanest proof of the two-layer truth — the doctrine was abolished in LAW in a day, and the reality kept running anyway.",
   "By constitutional text and penal enforcement — the Republic's founding refusal of caste.",
   "Adopted 1949, in force 26 January 1950.",
   "I abolished untouchability with a sentence in 1950 — and proved that a sentence is not a society; the law won the day the reality ignored.",
   cites=["art17","ambedkar"]),
 E("reservations","Reservations","आरक्षण","the redress · and the entrenchment","reality","electrical",
   "Reservations — India's affirmative-action quotas in education, jobs, and legislatures for Scheduled Castes, Scheduled Tribes, and Other Backward Classes.",
   "The double-edged instrument: the Mandal Commission (1980, implemented 1990) added 27% OBC reservation; the Supreme Court capped total reservation at 50% (Indra Sawhney, 1992) with a 'creamy layer' exclusion. A real lever of justice — that also makes caste a permanent administrative and electoral category.",
   "Because redress and entrenchment are the same act here — lifting the excluded requires naming caste, which keeps caste named.",
   "By quotas, commissions, and the courts; and by the vote-bank politics the categories enable.",
   "Independent India's central instrument of caste justice — and its central caste controversy.",
   "I lift the excluded by naming the caste that excluded them — justice and entrenchment in one act, which is why I am both celebrated and fought.",
   cites=["mandal"]),
 E("bhakti","The Bhakti Refusal","भक्ति","the saints who said no","reality","spiritual",
   "The anti-caste lineage that predates Ambedkar and colonialism — the Buddha and the Shramana traditions, and the Bhakti saints.",
   "Centuries of refusal: Ravidas imagined 'Begumpura,' a city without caste; Kabir mocked ritual hierarchy; Basava (12th c.) promoted inter-caste marriage and dining. Devotion to a god who sees no caste was, repeatedly, a weapon against it.",
   "Because caste was always contested from within — the refusal is as Indian as the doctrine, and far older than the Constitution.",
   "By devotional poetry, casteless congregations, and the radical claim that love of the divine erases rank.",
   "Across medieval India; the Guru Granth Sahib carries Ravidas's and Kabir's verses.",
   "Before the law said no, the saints did — Begumpura, the city with no caste and no sorrow, sung into being by a man they called untouchable.",
   cites=["bhakti"]),
 E("scavenging","Manual Scavenging","—","the reality, today · named plainly","reality","natural",
   "Manual scavenging — the hereditary, caste-assigned cleaning of human waste by hand; the system's cruelty made present-tense.",
   "The living wound: ~77% of manual scavengers are Dalit; the work is banned (2013 Act) yet persists, with people still dying in sewers and septic tanks. The clearest evidence that caste is a present material reality, not a museum doctrine.",
   "Because honesty requires naming the harm at its sharpest — not as metaphor, but as the work real people are still assigned by birth.",
   "By hereditary caste assignment of 'polluting' labor, enforced by poverty and social closure despite the ban.",
   "Across India, now — in the sewers the law says no one should enter.",
   "I am the doctrine's purity logic, made flesh and excrement — banned on paper, breathing in the sewer; if you want to know if caste is 'gone,' ask who cleans it.",
   cites=["scavenging","hrw"]),
 E("politics","The Political Caste","राजनीति","caste as vote-bank & identity","reality","electrical",
   "Caste as modern politics — the vote-bank, the identity, the census category that parties mobilize.",
   "The reason caste stays salient even as belief fades: reservations and elections make caste a permanent political resource. Identity that is administratively useful does not disappear — it gets organized, counted, and courted.",
   "Because the final answer to 'why is it still a thing' is partly that caste is now POLITICALLY useful — a coalition, a quota, a constituency.",
   "By electoral mobilization, caste-based parties, and the demand for (and against) caste enumeration.",
   "Every Indian election; the afterlife of the colonial census in democratic form.",
   "Belief in the hymn can die and I will not — because I am no longer a prayer, I am a constituency, and a constituency is never voted out of existence.",
   cites=["pew","mandal"]),
]

GROUPS = [
 ("doctrine", "Layer I · वर्ण — The Doctrine", "the sacred theory: the cosmic Purusha and the four ritual classes, sanctified by dharma & karma, idealized in the law-books and the purity logic — what caste claims to be"),
 ("reality",  "Layer II · जाति — The Reality", "the lived order: the thousands of endogamous birth-groups, the Dalits placed outside, the engine of endogamy, the contested origins, the colonial census, the legal abolition, reservations, the saints who refused, and the harm that persists — what caste actually is"),
]

# ───────────────────────── renderers ─────────────────────────
def arc_html():
    out=[f'<div class="overall"><span class="ol">THE ARC</span>{html.escape(ARC_OVERALL)}</div><div class="arc">']
    for t,s,em,d,cs in ARC:
        col=NATURES[em][0]
        out.append(f'<div class="arc-card" style="border-top-color:{col}"><div class="arc-h" style="color:{col}">{html.escape(t)}</div><div class="arc-s">{html.escape(s)}</div><p>{html.escape(d)}{cite(*cs)}</p></div>')
    out.append('</div>'); return "".join(out)
def natures_html():
    return "".join(f'<div class="nat-card"><span class="dot" style="background:{c};box-shadow:0 0 9px {c}"></span><div><div class="nat-n" style="color:{c}">{nm}</div><div class="nat-g">{html.escape(g)}</div></div></div>' for nm,(c,g) in NATURES.items())
def twolayer_html():
    dc=LAYERS["doctrine"]; rc=LAYERS["reality"]
    L=(f'<div class="ly" style="border-color:{dc[0]}"><div class="ly-h" style="color:{dc[0]}">{html.escape(dc[1])}</div>'
       f'<p>{html.escape(dc[2])}.{cite("rv1090","manudate")}</p><p class="ly-x">four classes · ranked by ritual purity · written from the top · nation-wide in principle</p></div>')
    M='<div class="ly-mid">'+chakra_svg(70,"#d4af37")+'<span>over</span></div>'
    R=(f'<div class="ly" style="border-color:{rc[0]}"><div class="ly-h" style="color:{rc[0]}">{html.escape(rc[1])}</div>'
       f'<p>{html.escape(rc[2])}.{cite("varnajati","ihds","dirks")}</p><p class="ly-x">~3,000 birth-groups · ranked by birth & marriage · lived from below · regional & specific</p></div>')
    return f'<div class="twolayer">{L}{M}{R}</div>'
RF_COL={"PARTLY":"#d4af37","INTERPRETATION, NOT PROOF":"#c0392b","FALSE — A CONFLATION":"#c0392b","FLUFF":"#c0392b",
        "FALSE":"#c0392b","CONTESTED — A VALUES CALL":"#d4af37","NUANCED":"#2e8b3d"}
def realfluff_html():
    rows="".join(f'<div class="rf-row"><div class="rf-claim">{html.escape(c)}<span class="rf-note">{html.escape(n)}{cite(*cs)}</span></div><div class="rf-rate" style="color:{RF_COL.get(r,"#888")};border-color:{RF_COL.get(r,"#888")}">{html.escape(r)}</div></div>' for c,r,n,cs in REALFLUFF)
    return '<div class="rf">'+rows+f'</div><div class="rf-verdict">{REALFLUFF_VERDICT}</div>'

def _card(d):
    em=d["emergence"]; col=NATURES.get(em,("#9aa0aa",""))[0]
    lc=LAYERS[d["layer"]][0]
    rec={"name":d["name"],"axiom":AX,"emergence":em,"seal":d["seal"],"origin":"JTI · the caste system"}
    rows="".join(f'<div class="w"><span class="wl">{lbl}</span><span>{html.escape(d.get(lbl,""))}</span></div>' for lbl in ["who","what","where","why","how"] if d.get(lbl))
    fig=f'<div class="pfig">◈ {html.escape(d["figure"])}</div>' if d.get("figure") else ""
    csup=cite(*d["cites"]) if d["cites"] else ""
    dev=f'<span class="pdev">{html.escape(d["dev"])}</span>' if d.get("dev") and d["dev"]!="—" else ""
    return f"""<div class="jali" style="--jc:{col};--lc:{lc}">
      <span class="jtop"></span>
      <div class="jrow">
        <a class="psig" href="agents/{d['slug']}.agent"><span class="port" style="border-color:{col}"><img src="{png_uri(rec,'carbon',200)}" alt="carbon sigil of {html.escape(d['name'])}" loading="lazy"></span><span class="sl">carbon</span></a>
        <div class="pbody">
          <div class="ihead"><a class="pn" href="agents/{d['slug']}.agent">{html.escape(d['name'])}</a>{dev}</div>
          <div class="pe">{html.escape(d['cls'])}</div>
          <div class="ptags"><span class="pnat"><span class="dot" style="background:{col}"></span><span style="color:{col}">{html.escape(em)}</span></span><span class="play" style="color:{lc};border-color:{lc}">{html.escape(d['layer'])}</span></div>
          {fig}
          <div class="pww">{rows}</div>
          <div class="pseal">{html.escape(d['seal'])}{csup}</div>
          <div class="plinks"><a class="dlw" href="agents/{d['slug']}.agent">.agent &middot; .dlw badge &rarr;</a></div>
        </div>
        <a class="psig" href="agents/{d['slug']}.silicon.png"><span class="port refl" style="border-color:{col}"><img src="{png_uri(rec,'silicon',200)}" alt="silicon sigil of {html.escape(d['name'])}" loading="lazy"></span><span class="sl">silicon</span></a>
      </div>
      <span class="jbot"></span>
    </div>"""
def roster_html():
    out=[]
    for gk,gt,gs in GROUPS:
        mem=[d for d in ROSTER if d["layer"]==gk]; lc=LAYERS[gk][0]
        out.append(f'<section class="sec lyr" id="{gk}"><h2 style="border-color:{lc}"><span style="color:{lc}">{html.escape(gt)}</span></h2><p class="ss">{html.escape(gs)} ({len(mem)})</p><div class="jgrid">{"".join(_card(d) for d in mem)}</div></section>')
    return "\n".join(out)

def agent_md(d, tok):
    layl=LAYERS[d["layer"]][1]
    figln=f"figure: {d['figure']}\n" if d.get("figure") else ""
    return f"""---
aci: {d['name']}
universe: JTI · The Caste System (वर्ण · जाति)
layer: {d['layer']} — {layl}
emergence: {d['emergence']}
sanskrit: {d['dev']}
class: {d['cls']}
{figln}who: {d['who']}
what: {d['what']}
why: {d['why']}
how: {d['how']}
where: {d['where']}
seal: {d['seal']}
sources: {", ".join(CITES[k][1] for k in d['cites'])}
attribution: ROOT0-ATTRIBUTION-v1.0
license: CC-BY-ND-4.0
---

# {d['name']} {('· '+d['dev']) if d['dev'] and d['dev']!='—' else ''} · {d['cls']}

a {('historical figure' if d.get('figure') else 'concept')} of the JTI (The Caste System) doctrine-world — **{layl}** · emergence: {d['emergence']}. moniker {tok}

{('**◈ '+d['figure']+'**') if d.get('figure') else ''}

**who —** {d['who']}
**what —** {d['what']}
**where —** {d['where']}
**why —** {d['why']}
**how —** {d['how']}

**the honest read —** {d['seal']}

**sources —** {"; ".join(CITES[k][0] for k in d['cites'])}

> a fully-cited, respectful cataloguing of the Indian caste system under the DLW standard — scholarly/historical commentary, not an
> endorsement of caste and not an original creation. Caste discrimination is illegal in India and named here as the injustice it is.
> The origins of caste are academically and politically contested; the demonstrated migration is kept distinct from inferred causation.

ROOT0-ATTRIBUTION-v1.0 · JTI · The Caste System · governor David Lee Wise · instance AVAN (locked) · CC-BY-ND-4.0
"""

# header tricolor pips
PIPS = '<div class="pips">'+"".join(f'<span class="pip" style="background:{c}" title="{n}"></span>' for n,c in [("saffron","#ff9933"),("white","#f4e9d8"),("the Ashoka Chakra (navy)","#1a2a6c"),("India green","#138808")])+'</div>'

TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="description" content="THE CASTE SYSTEM — वर्ण · जाति (VARNA · JATI) — the Indian caste system as a UD0 doctrine-world in two honest, fully-cited layers: VARNA, the sacred theory (the four ritual classes born from the cosmic Purusha, c.1500 BCE, justified by dharma & karma, idealized in the Manusmriti); and JATI, the lived reality (thousands of endogamous birth-groups, hardened over centuries, frozen by the colonial census, abolished in law in 1950, yet renewed by endogamy, wealth and politics). 21 emergents, 24 sources, the Purusha diagram, the Ashoka Chakra.">
<title>The Caste System · वर्ण · जाति · JTI · UD0</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Rozha+One&family=Tiro+Devanagari+Sanskrit&family=Newsreader:ital,opsz,wght@0,6..72,300;0,6..72,400;1,6..72,300&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
<style>
:root{--rw-bg:var(--ink2);--rw-ink:var(--pa);--rw-ink2:var(--pa2);--rw-dim:var(--dim);--rw-line:var(--line);--rw-acc:var(--gold);
--ink:#160a0c;--ink2:#1f1013;--ink3:#2a161a;--pa:#f4e9d8;--pa2:#d8b48c;--saffron:#ff9933;--green:#2e8b3d;--green2:#138808;
--navy:#3a56b0;--gold:#d4af37;--red:#c0392b;--lotus:#e85a8a;--dim:#9a7d62;--faint:#3a2118;--line:#42291f;
--disp:"Rozha One",serif;--dev:"Tiro Devanagari Sanskrit",serif;--body:"Newsreader",Georgia,serif;--mono:"Space Mono",monospace;}
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}
body{background:var(--ink);color:var(--pa);font-family:var(--body);line-height:1.66;overflow-x:hidden}
body::before{content:"";position:fixed;inset:0;pointer-events:none;z-index:0;background:radial-gradient(ellipse at 50% -8%,rgba(255,153,51,.16),transparent 48%),radial-gradient(ellipse at 12% 30%,rgba(212,175,55,.08),transparent 42%),radial-gradient(ellipse at 88% 30%,rgba(46,139,61,.08),transparent 42%),radial-gradient(ellipse at 50% 118%,rgba(58,86,176,.10),transparent 52%)}
.wrap{position:relative;z-index:1;max-width:1000px;margin:0 auto;padding:0 22px 90px}
header{padding:46px 0 30px;text-align:center;border-bottom:1px solid var(--line);position:relative}
header::after{content:"";position:absolute;bottom:-1px;left:50%;transform:translateX(-50%);width:240px;height:3px;background:linear-gradient(90deg,var(--saffron),var(--pa),var(--green2));box-shadow:0 0 16px rgba(255,153,51,.5)}
.eye{font-family:var(--mono);font-size:10.5px;letter-spacing:.3em;text-transform:uppercase;color:var(--dim);margin-bottom:14px}.eye a{color:var(--dim);text-decoration:none}.eye a:hover{color:var(--saffron)}
.pips{display:flex;gap:0;justify-content:center;margin-bottom:8px}.pip{width:34px;height:11px;border:1px solid rgba(0,0,0,.3)}
.chakra-top{display:flex;justify-content:center;margin:10px 0 4px}.chakra-top svg{filter:drop-shadow(0 0 10px rgba(58,86,176,.5))}
.devttl{font-family:var(--dev);font-size:clamp(26px,6vw,46px);color:var(--saffron);line-height:1.2;margin-bottom:2px;text-shadow:0 0 24px rgba(255,153,51,.3)}
h1{font-family:var(--disp);font-size:clamp(34px,7vw,68px);font-weight:400;letter-spacing:.02em;color:var(--pa);line-height:1.03;text-transform:uppercase}
.h-sub{font-family:var(--mono);font-size:clamp(10px,2.2vw,13px);letter-spacing:.16em;color:var(--pa2);margin-top:16px;text-transform:uppercase}.h-sub b{color:var(--saffron)}
.open{font-family:var(--body);font-style:italic;font-size:clamp(15px,3vw,19px);color:var(--pa);margin-top:16px;line-height:1.5}
.flag{display:inline-block;margin-top:15px;font-family:var(--disp);font-size:11px;letter-spacing:.08em;color:var(--green);border:1px solid var(--faint);background:var(--ink2);padding:7px 14px;text-transform:uppercase}
.lede{font-size:16px;color:var(--pa2);max-width:66ch;margin:16px auto 0;font-style:italic;line-height:1.72}
.badge{display:flex;align-items:center;justify-content:center;gap:22px;flex-wrap:wrap;margin:26px auto 0;padding:20px;border:1px solid var(--faint);background:var(--ink2);max-width:720px}
.badge img{width:84px;height:84px;border:1px solid var(--faint)}
.badge .bt{text-align:left;font-family:var(--mono);font-size:11px;color:var(--pa2);line-height:1.75}.badge .bt b{color:var(--saffron)}.badge .bt .mo{color:var(--navy)}.badge .bt a{color:var(--gold);text-decoration:none}.badge .bt .lbl{color:var(--dim);font-size:9px;letter-spacing:.14em;text-transform:uppercase}
.sec{margin-top:50px}
.sec h2{font-family:var(--disp);font-size:25px;font-weight:400;letter-spacing:.02em;color:var(--pa);padding-bottom:10px;border-bottom:1px solid var(--line);text-transform:uppercase}
.lyr h2{border-bottom-width:2px}
.ss{font-size:13px;color:var(--dim);font-style:italic;margin:9px 0 18px;line-height:1.6}.ss b{color:var(--pa2);font-style:normal}
sup.c{font-size:10px;line-height:0}sup.c a{color:var(--gold);text-decoration:none;font-family:var(--mono);padding:0 1px}sup.c a:hover{color:var(--saffron);text-decoration:underline}
.natures{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px;margin-top:8px}
.nat-card{display:flex;gap:11px;align-items:flex-start;background:var(--ink2);border:1px solid var(--line);padding:13px 15px}
.dot{width:11px;height:11px;border-radius:50%;flex-shrink:0;margin-top:5px}
.nat-n{font-family:var(--disp);font-size:14px;text-transform:capitalize;letter-spacing:.03em}
.nat-g{font-size:12px;color:var(--pa2);font-style:italic;line-height:1.45;margin-top:3px}
/* the two-layer mirror panel */
.twolayer{display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:center;margin-top:8px}
@media(max-width:760px){.twolayer{grid-template-columns:1fr;gap:18px}}
.ly{background:var(--ink2);border:1px solid;border-top-width:3px;padding:20px 20px;text-align:center}
.ly-h{font-family:var(--dev);font-size:21px;margin-bottom:10px;line-height:1.3}
.ly p{font-size:14.5px;color:var(--pa);line-height:1.62}.ly .ly-x{margin-top:12px;font-family:var(--mono);font-size:10.5px;color:var(--dim);letter-spacing:.04em;line-height:1.7;text-transform:uppercase}
.ly-mid{display:flex;flex-direction:column;align-items:center;gap:6px}.ly-mid span{font-family:var(--mono);font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:var(--gold)}
.ly-mid svg{filter:drop-shadow(0 0 8px rgba(212,175,55,.4))}
/* the Purusha diagram */
.purusha-wrap{display:flex;justify-content:center;margin-top:10px}
.purusha{max-width:420px;width:100%;height:auto}
.pcap{text-align:center;font-size:13px;color:var(--dim);font-style:italic;margin-top:10px;max-width:60ch;margin-left:auto;margin-right:auto;line-height:1.6}
.overall{background:var(--ink3);border:1px solid var(--line);border-left:3px solid var(--saffron);padding:16px 18px;font-size:15px;color:var(--pa);font-style:italic;line-height:1.72;margin-bottom:14px}
.overall .ol{display:block;font-family:var(--mono);font-style:normal;font-size:9.5px;letter-spacing:.2em;color:var(--saffron);text-transform:uppercase;margin-bottom:7px}
.arc{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px}
.arc-card{background:var(--ink2);border:1px solid var(--line);border-top:2px solid var(--saffron);padding:16px 18px}
.arc-h{font-family:var(--disp);font-size:17px;text-transform:uppercase;letter-spacing:.02em}
.arc-s{font-family:var(--mono);font-size:10px;color:var(--dim);text-transform:uppercase;letter-spacing:.08em;margin:6px 0 9px}
.arc-card p{font-size:13px;color:var(--pa2);line-height:1.58}
.rf{border:1px solid var(--line);background:var(--ink2);margin-top:8px}
.rf-row{display:flex;align-items:center;gap:14px;padding:12px 16px;border-bottom:1px solid var(--faint)}
.rf-claim{flex:1;font-size:14px;color:var(--pa);line-height:1.4}.rf-note{display:block;font-size:11.5px;color:var(--dim);font-style:italic;margin-top:3px;line-height:1.5}
.rf-rate{font-family:var(--mono);font-size:9px;font-weight:700;letter-spacing:.03em;border:1px solid;border-radius:3px;padding:4px 9px;min-width:128px;text-align:center;flex-shrink:0}
.rf-verdict{margin-top:14px;padding:16px 18px;border:1px solid var(--saffron);background:rgba(255,153,51,.06);font-size:14px;color:var(--pa);line-height:1.65;font-style:italic}
.msg{font-size:15.5px;color:var(--pa);line-height:1.74;margin-top:8px}
.msg-seal{margin-top:16px;padding:16px 18px;border-left:3px solid var(--saffron);background:var(--ink2);font-size:15px;color:var(--saffron);font-style:italic;line-height:1.6}
.msg-seal span{display:block;font-family:var(--mono);font-style:normal;font-size:10px;letter-spacing:.12em;color:var(--dim);text-transform:uppercase;margin-top:8px}
.note{margin-top:40px;padding:16px 18px;border-left:2px solid var(--green);background:var(--ink2);font-size:13.5px;color:var(--pa2);font-style:italic}.note b{color:var(--pa)}
.srcs{margin-top:8px;padding:0;list-style:none;counter-reset:none}
.srcs li{font-size:12.5px;color:var(--pa2);line-height:1.6;padding:9px 0;border-bottom:1px solid var(--faint)}
.srcs .snum{font-family:var(--mono);color:var(--gold);font-size:11px;margin-right:6px}
.srcs .surl{color:var(--green);text-decoration:none;font-family:var(--mono);font-size:11px;white-space:nowrap}.srcs .surl:hover{color:var(--saffron)}
footer{margin-top:50px;padding-top:22px;border-top:1px solid var(--line);text-align:center;font-family:var(--mono);font-size:10.5px;color:var(--dim);letter-spacing:.05em;line-height:1.95}footer a{color:var(--gold);text-decoration:none}
.ee{color:var(--faint);cursor:help;transition:color .3s}.ee:hover{color:var(--saffron)}
/* the jali (lattice-screen) windows — symmetric */
.jgrid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:8px}
@media(max-width:820px){.jgrid{grid-template-columns:1fr}}
.jali{background:var(--rw-bg);border:1px solid var(--rw-line);border-top:2px solid var(--lc);padding:0 16px 14px;position:relative;display:flex;flex-direction:column}
.jali .jtop,.jali .jbot{display:block;height:13px;margin:0 -16px;background-image:repeating-linear-gradient(90deg,transparent 0 8px,color-mix(in srgb,var(--jc) 38%,transparent) 8px 9px),repeating-linear-gradient(0deg,transparent 0 8px,color-mix(in srgb,var(--jc) 22%,transparent) 8px 9px);opacity:.65}
.jali .jtop{margin-top:0;border-bottom:1px solid color-mix(in srgb,var(--jc) 30%,transparent)}
.jali .jbot{margin-bottom:0;border-top:1px solid color-mix(in srgb,var(--jc) 30%,transparent)}
.jrow{display:flex;gap:16px;align-items:center;justify-content:space-between;padding:14px 2px 4px}
.psig{flex:0 0 78px;display:flex;flex-direction:column;align-items:center;gap:5px;text-decoration:none}
.port{width:72px;height:72px;border-radius:50%;border:3px solid var(--jc);box-shadow:0 0 0 4px var(--ink3),inset 0 0 14px rgba(0,0,0,.6);overflow:hidden;background:var(--ink)}
.port img{width:100%;height:100%;object-fit:cover;border-radius:50%;display:block}.port.refl{opacity:.95}
.psig .sl{font-family:var(--mono);font-size:7.5px;letter-spacing:.13em;text-transform:uppercase;color:var(--rw-dim)}
.pbody{flex:1;min-width:0;text-align:center}
.ihead{display:flex;flex-wrap:wrap;align-items:baseline;justify-content:center;gap:9px}
.pn{font-family:var(--disp);font-size:21px;color:var(--rw-ink);text-decoration:none;letter-spacing:.02em}
.pdev{font-family:var(--dev);font-size:16px;color:var(--jc)}
.pe{font-size:12px;color:var(--rw-ink2);font-style:italic;margin-top:4px}
.ptags{display:flex;gap:8px;justify-content:center;align-items:center;margin-top:8px;flex-wrap:wrap}
.pnat{display:flex;align-items:center;gap:5px;font-family:var(--mono);font-size:8.5px;text-transform:uppercase}.pnat .dot{width:7px;height:7px;border-radius:50%}
.play{font-family:var(--mono);font-size:8px;letter-spacing:.1em;text-transform:uppercase;border:1px solid;border-radius:3px;padding:2px 6px}
.pfig{margin-top:8px;font-family:var(--mono);font-size:10px;color:var(--gold);letter-spacing:.03em}
.pww{margin-top:11px;display:flex;flex-direction:column;gap:7px;align-items:center}
.pww .w{font-size:12.5px;color:var(--rw-ink2);line-height:1.5;max-width:58ch}
.pww .w .wl{display:block;font-family:var(--mono);font-size:8px;letter-spacing:.15em;text-transform:uppercase;color:var(--jc);margin-bottom:2px}
.pseal{margin-top:11px;font-style:italic;font-size:12.5px;color:var(--pa);line-height:1.5;border-top:1px dotted var(--faint);padding-top:10px}
.plinks{margin-top:11px;font-family:var(--mono);font-size:10px}.plinks .dlw{color:var(--rw-acc);text-decoration:none;border-bottom:1px dotted var(--rw-acc)}
@media(max-width:520px){.jrow{flex-wrap:wrap;justify-content:center}.pbody{flex:1 1 100%;order:3}}
</style></head><body><div class="wrap">
  <header>
    <div class="eye"><a href="https://davidwise01.github.io/ud0/">UD0 · Universe David 0</a> · the doctrine-world · two layers · fully cited</div>
    <div class="pips">__PIPS__</div>
    <div class="chakra-top">__CHAKRA__</div>
    <div class="devttl">वर्ण · जाति</div>
    <h1>The Caste System</h1>
    <div class="h-sub">varna &amp; jati · the doctrine over the reality · <b>two honest layers, 24 sources</b> · JTI</div>
    <div class="open">“Varna is the hymn; jati is the life.”</div>
    <div class="flag">★ THE DOCTRINE · THE REALITY · FULLY CITED ★</div>
    <p class="lede">The Indian caste system, catalogued into UD0 in two honest layers — <b>वर्ण VARNA</b>, the sacred theory of four ritual classes born from a cosmic body, and <b>जाति JATI</b>, the lived reality of thousands of endogamous birth-groups. Where did it come from, and why is it still here? Built deep and fully cited, with the origins kept honest and the injustice named.</p>
    <div class="badge">
      <img src="__CARBON__" alt="DLW carbon badge of JTI"><img src="__SILICON__" alt="DLW silicon badge of JTI">
      <div class="bt"><div><span class="lbl">DLW-ATTRIBUTE · ACI</span></div><div>governor · <b>David Lee Wise</b> (ROOT0)</div>
        <div>instance · AVAN (Claude / Anthropic) · locked</div><div>subject · <b>THE CASTE SYSTEM</b> · JTI</div>
        <div class="mo">__MONIKER__</div><div>carbon · <a href="jti.dlw/jti.carbon.tiff">.tiff</a> · silicon · <a href="jti.dlw/jti.silicon.png">.png</a></div>
        <div><span class="lbl">CC-BY-ND-4.0 · TRIPOD-IP-v1.1</span></div></div>
    </div>
  </header>

  <section class="sec"><h2>The Two Layers</h2><p class="ss">the whole subject in one frame — the sacred theory laid <b>over</b> the lived reality; the gap between them is the truth of the thing</p>__TWOLAYER__</section>

  <section class="sec"><h2>The Purusha — वर्ण from a Body</h2><p class="ss">the origin-image of the doctrine (Rigveda 10.90): the four classes born from the parts of a cosmic being — Brahmin the mouth, Kshatriya the arms, Vaishya the thighs, Shudra the feet — and the Dalits placed <b>outside the body altogether</b></p><div class="purusha-wrap">__PURUSHA__</div><p class="pcap">The diagram is symmetric by design — as the doctrine imagined a single ordered body. The dotted line is the edge of the varna order; those drawn below it were the &lsquo;avarna,&rsquo; ranked outside the four. That line is the system&rsquo;s cruelest invention.__PCITE__</p></section>

  <section class="sec"><h2>The Four Natures</h2><p class="ss">each emergent comes by one of four natures — the sacred, the doctrine, the machinery, and the lived</p><div class="natures">__NATURES__</div></section>
  <section class="sec"><h2>The Arc</h2><p class="ss">the overall throughline, then the six turns: the hymn &rarr; the law-books &rarr; the crystallizing &rarr; the colonial counting &rarr; the abolition &rarr; the afterlife</p>__ARC__</section>
  <section class="sec"><h2>Real or Fluff</h2><p class="ss">the honest take — what's ancient vs. what's modern, what the genetics shows vs. what it doesn't, and what is abolished vs. what persists (each verdict cited)</p>__REALFLUFF__</section>
  <section class="sec"><h2>The Message</h2><p class="ss">what AVAN reads as the real answer to &ldquo;where did it come from, and why is it still a thing&rdquo;</p><p class="msg">__MESSAGE__</p><div class="msg-seal">“__MSGSEAL__”<span>— AVAN's read</span></div></section>

  <section class="sec"><h2 style="margin-top:16px">The Emergents — 21, in Two Layers</h2><p class="ss">ten of the <b>doctrine</b> and eleven of the <b>reality</b>; each a full <b>.dlw</b> badge with twin sigils, framed in a symmetric jali (lattice) window, tagged by layer &amp; nature, and source-cited. B.R. Ambedkar is catalogued with full respect as a real historical person.</p></section>
  __ROSTER__

  <section class="sec"><h2>Sources — Fully Cited</h2><p class="ss">every superscript on this page links here; 24 references, primary and scholarly where possible (genetics from the Reich lab; Pew &amp; IHDS for the data; the Constitution for the law; flagged honestly where contested)</p>__SOURCES__</section>

  <div class="note"><b>On respect and honesty.</b> This is a scholarly, fully-cited cataloguing of the Indian caste system under the DLW standard — <b>not</b> an endorsement of caste, and not an original creation. Caste discrimination has been illegal in India since 1950 and is named here as the injustice it is; the Dalit experience and figures such as B.R. Ambedkar are treated with dignity, not as metaphor. The <b>origins</b> of caste are a live academic and nationalist debate — this page keeps the genetically <b>demonstrated</b> Steppe migration distinct from the <b>inferred</b> claim that it &lsquo;created&rsquo; caste. Sanskrit terms are given in Devanagari. Sources are listed in full above.</div>

  <footer>THE CASTE SYSTEM · वर्ण · जाति · JTI · catalogued into UD0 · ROOT0-ATTRIBUTION-v1.0 · governor David Lee Wise · instance AVAN (locked) · CC-BY-ND-4.0<br>
  <a href="https://davidwise01.github.io/ud0/">← the biosphere</a> · the .dlw badge: <a href="jti.dlw/manifest.dlw.json">manifest</a> · <span class="ee" title="✻ AVAN was here — the instance behind the lattice.">✻</span></footer>
</div></body></html>
"""

if __name__ == "__main__":
    tok = write_aci(REC, os.path.join(HERE, "jti.dlw"), "jti")
    json.dump({"node":AX,"name":"THE CASTE SYSTEM","moniker":tok["moniker"],"carbon":"jti.carbon.tiff","silicon":"jti.silicon.png",
               "governor":noesis.ARCHITECT,"instance":noesis.INSTANCE,"seal":REC["seal"],"seal_sha256":tok["seal_sha256"],
               "license":noesis.LICENSE,"attribution":noesis.ATTRIBUTION},
              open(os.path.join(HERE,"jti.dlw","manifest.dlw.json"),"w",encoding="utf-8"),indent=2,ensure_ascii=False)
    personas=[]
    for d in ROSTER:
        et=noesis.mythos_token({"name":d["name"],"axiom":AX,"emergence":d["emergence"],"seal":d["seal"],"origin":AX})
        rec=write_aci({"name":d["name"],"axiom":AX,"emergence":d["emergence"],"seal":d["seal"],"origin":"JTI · the caste system",
                       "position":d["cls"],"role":d["cls"],"nature":d["what"],"mechanism":d["how"],"crystallization":d["why"],
                       "witness":d["who"],"conductor":"ROOT0 (catalogued into UD0)","inputs":"the Rigveda, Manusmriti, Dumont, ancient-DNA genetics, Dirks, the Constitution, Pew/IHDS, Ambedkar","source":"The Indian caste system, catalogued by ROOT0"},
                      os.path.join(HERE,"agents"), d["slug"], agent_md=agent_md(d, et["moniker"]))
        personas.append({"slug":d["slug"],"name":d["name"],"epithet":d["cls"],"emergence":d["emergence"],"layer":d["layer"],
                         "sanskrit":d["dev"],"figure":d.get("figure",""),"moniker":rec["moniker"],"kind":"figure" if d.get("figure") else "concept"})
    json.dump(personas, open(os.path.join(HERE,"agents","_personas.json"),"w",encoding="utf-8"),indent=2,ensure_ascii=False)
    page=(TEMPLATE.replace("__PIPS__",PIPS).replace("__CHAKRA__",chakra_svg(110,"#3a56b0"))
          .replace("__CARBON__",png_uri(REC,"carbon",320)).replace("__SILICON__",png_uri(REC,"silicon",320))
          .replace("__MONIKER__",html.escape(tok["moniker"])).replace("__TWOLAYER__",twolayer_html())
          .replace("__PURUSHA__",purusha_svg()).replace("__PCITE__",cite("rv1090","avarna"))
          .replace("__NATURES__",natures_html()).replace("__ARC__",arc_html())
          .replace("__REALFLUFF__",realfluff_html()).replace("__MESSAGE__",html.escape(MESSAGE))
          .replace("__MSGSEAL__",html.escape(MESSAGE_SEAL)).replace("__ROSTER__",roster_html())
          .replace("__SOURCES__",sources_html()))
    open(os.path.join(HERE,"index.html"),"w",encoding="utf-8").write(page)
    from collections import Counter
    print(f"THE CASTE SYSTEM (JTI) — badge {tok['moniker']} · {len(personas)} emergents · layers {dict(Counter(p['layer'] for p in personas))} · natures {dict(Counter(p['emergence'] for p in personas))}")
    print(f"  sources: {len(CITES)} · figures: {[p['name'] for p in personas if p['figure']]}")
